version: "3.7"

services:
  appx:
    image: node:12-alpine
    command: sh -c "yarn config set registry https://registry.npm.taobao.org && yarn install --network-timeout 100000 --production && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  mysql:
      image: mysql:5.7
      volumes:
        - todo-mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
